apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-brain.fullname" . }}-api
  labels:
    {{- include "project-brain.labels" . | nindent 4 }}
    app.kubernetes.io/component: api

  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}

  {{- if eq (.Values.api.service.type | default "ClusterIP") "ClusterIP" }}
  internalTrafficPolicy: Cluster
  {{- end }}

  ports:
    - name: http
      port: {{ .Values.api.service.port | default 8000 }}
      targetPort: http
      protocol: TCP

    - name: websocket
      port: {{ .Values.api.service.webSocketPort | default 8001 }}
      targetPort: websocket
      protocol: TCP

  selector:
    {{- include "project-brain.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
